/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ['class'],
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        // ── Phase 3 Design System: CSS-variable-driven (respects .dark toggle) ──
        'az-bg':             'var(--az-bg)',
        'az-bg-alt':         'var(--az-bg-alt)',
        'az-surface':        'var(--az-surface)',
        'az-surface-solid':  'var(--az-surface-solid)',
        'az-border':         'var(--az-border)',
        'az-border-strong':  'var(--az-border-strong)',
        'az-text':           'var(--az-text)',
        'az-text-secondary': 'var(--az-text-secondary)',
        'az-text-muted':     'var(--az-text-muted)',

        // Accent
        'az-accent':         'var(--az-accent)',
        'az-accent-hover':   'var(--az-accent-hover)',
        'az-accent-subtle':  'var(--az-accent-subtle)',
        'az-accent-border':  'var(--az-accent-border)',

        // Semantic
        'az-success':        'var(--az-success)',
        'az-success-subtle': 'var(--az-success-subtle)',
        'az-warning':        'var(--az-warning)',
        'az-warning-subtle': 'var(--az-warning-subtle)',
        'az-danger':         'var(--az-danger)',
        'az-danger-subtle':  'var(--az-danger-subtle)',
        'az-info':           'var(--az-info)',

        // Legacy aliases (now var()-driven, same as primary tokens)
        'az-black':          'var(--az-surface-solid)',
        'az-card':           'var(--az-surface-solid)',
        'az-card-elevated':  'var(--az-surface-solid)',
        'az-border-bright':  'var(--az-border-strong)',
        'az-emerald':        'var(--az-success)',
        'az-blue':           'var(--az-info)',
        'az-purple':         'var(--az-accent)',
        'az-amber':          'var(--az-warning)',
        'az-red':            'var(--az-danger)',
        'az-cyan':           'var(--az-info)',

        // ── shadcn/ui compatibility (mapped to CSS vars) ──
        background: 'var(--background)',
        foreground: 'var(--foreground)',
        card: { DEFAULT: 'var(--card)', foreground: 'var(--card-foreground)' },
        popover: { DEFAULT: 'var(--popover)', foreground: 'var(--popover-foreground)' },
        primary: { DEFAULT: 'var(--primary)', foreground: 'var(--primary-foreground)' },
        secondary: { DEFAULT: 'var(--secondary)', foreground: 'var(--secondary-foreground)' },
        muted: { DEFAULT: 'var(--muted)', foreground: 'var(--muted-foreground)' },
        accent: { DEFAULT: 'var(--accent)', foreground: 'var(--accent-foreground)' },
        destructive: { DEFAULT: 'var(--destructive)', foreground: 'var(--destructive-foreground)' },
        border: 'var(--border)',
        input: 'var(--input)',
        ring: 'var(--ring)',
      },
      fontFamily: {
        sans: ['Plus Jakarta Sans', 'Inter', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      borderRadius: {
        '2xl': '16px',
        lg: '12px',
        md: '10px',
        sm: '8px',
        'az-lg': '20px',
        'az-md': '14px',
        'az-sm': '10px',
        'az-pill': '999px',
      },
      backdropBlur: {
        xs: '2px',
        glass: '20px',
      },
      boxShadow: {
        'az-card':       '0 4px 20px rgba(17,17,17,0.04), 0 1px 3px rgba(17,17,17,0.02)',
        'az-card-hover': '0 8px 30px rgba(17,17,17,0.08), 0 4px 10px rgba(17,17,17,0.04)',
        'az-glass':      '0 8px 32px rgba(17,17,17,0.06), inset 0 1px 0 rgba(255,255,255,0.8)',
        'az-modal':      '0 24px 64px rgba(17,17,17,0.15), 0 0 0 1px rgba(17,17,17,0.06)',
        'az-focus':      '0 0 0 3px rgba(108,79,209,0.18)',

        'sn-button':        '0 1px 2px rgba(0,0,0,0.35), inset 0 1px 0 rgba(255,255,255,0.05)',
        'sn-button-active': '0 0 0 rgba(0,0,0,0), inset 0 1px 2px rgba(0,0,0,0.3)',
        'sn-dropdown':      '0 8px 32px rgba(0,0,0,0.5), 0 0 0 1px rgba(108,95,199,0.1)',
        'sn-modal':         '0 24px 64px rgba(0,0,0,0.6), 0 0 0 1px rgba(108,95,199,0.15)',
        'sn-card':          '0 1px 3px rgba(0,0,0,0.3), 0 0 0 1px rgba(42,39,50,0.5)',
        'sn-card-hover':    '0 4px 24px rgba(0,0,0,0.4), 0 0 0 1px rgba(108,95,199,0.2)',
        'sn-input-focus':   '0 0 0 3px rgba(108,95,199,0.15)',
        'sn-glow':          '0 0 20px rgba(108,95,199,0.15)',
        'sn-tooltip':       '0 4px 12px rgba(0,0,0,0.5), 0 0 0 1px rgba(108,95,199,0.1)',
      },
      keyframes: {
        'fade-in':   { from: { opacity: 0, transform: 'translateY(4px)' }, to: { opacity: 1, transform: 'translateY(0)' } },
        'slide-in':  { from: { transform: 'translateX(-10px)', opacity: 0 }, to: { transform: 'translateX(0)', opacity: 1 } },
        'slide-in-right': { from: { transform: 'translateX(100%)' }, to: { transform: 'translateX(0)' } },
        'scale-in':  { from: { transform: 'scale(0.97)', opacity: 0 }, to: { transform: 'scale(1)', opacity: 1 } },
        'phone-in':  { from: { transform: 'scale(0.92)', opacity: 0 }, to: { transform: 'scale(1)', opacity: 1 } },
        'pulse-dot': { '0%,100%': { opacity: 1 }, '50%': { opacity: 0.4 } },
        shimmer:     { '0%': { backgroundPosition: '-200% 0' }, '100%': { backgroundPosition: '200% 0' } },
      },
      animation: {
        'fade-in':   'fade-in 0.25s ease-out',
        'slide-in':  'slide-in 0.25s ease-out',
        'slide-in-right': 'slide-in-right 0.3s ease-out',
        'scale-in':  'scale-in 0.2s ease-out',
        'phone-in':  'phone-in 0.35s cubic-bezier(0.34, 1.56, 0.64, 1)',
        'pulse-dot': 'pulse-dot 2s ease-in-out infinite',
        shimmer:     'shimmer 1.6s linear infinite',
      },
      transitionTimingFunction: {
        'sn-spring': 'cubic-bezier(0.34, 1.56, 0.64, 1)',
        'sn-ease':   'cubic-bezier(0.4, 0, 0.2, 1)',
      },
    },
  },
  plugins: [],
};
